# SPDX-License-Identifier: BSD-2-Clause
stages:
    - "verify"

.verify:
    script:
        - "python -m venv /opt/venv"
        - "source /opt/venv/bin/activate; pip install --upgrade pip"
        - "source /opt/venv/bin/activate; pip install -r requirements/dev.txt"
        - "source /opt/venv/bin/activate; invoke test"

verify-3.6:
    extends: ".verify"
    stage: "verify"
    image: "python:3.6"

verify-3.7:
    extends: ".verify"
    stage: "verify"
    image: "python:3.7"

verify-3.8:
    extends: ".verify"
    stage: "verify"
    image: "python:3.8"
